# -*- coding: utf-8 -*-
"""lendo, visualizando, analisando e rotacionando

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d_jkCPhoyzSTxGg49ujpg9vNiSlsa2RU

# Aula PID - 28/02/2024
Adaptada

[1] http://poynton.ca/PDFs/ColorFAQ.pdf

[2] GONZALEZ, Rafael C.; WOODS, Richard C. Processamento digital de imagens . Pearson Educación, 2009.

[3] https://colab.research.google.com/github/gbnegrini/monitoria-processamento-imagens/blob/main/INF0018_2_Manipulacao_Basica.ipynb

# \**Bibliotecas e pacotes**
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
# %matplotlib inline

"""# Carregando uma Imagem

Para carregar e manipular uma imagem, primeiro é preciso fazer o upload um arquivo de imagem no ambiente virtual do Google Colab:


1.   Clique no ícone da pastinha no menu lateral esquerdo.
2.   Utilize o ícone de upload ou arraste o arquivo desejado para a área do menu lateral.

Após o upload, o arquivo estará disponível no diretório base do ambiente.

A função ***imread()*** do openCV é utilizada para carregar uma imagem de um arquivo. Basta passar como argumentos o caminho do arquivo e o modo de abertura (escala de cinza ou colorido).
"""

img_PID_2024 = cv2.imread("/content/968d4064-1c6a-40dd-a825-0d93debe5ad9.jpg", cv2.IMREAD_GRAYSCALE)

img_PID_2024r = cv2.imread("/content/968d4064-1c6a-40dd-a825-0d93debe5ad9.jpg")

from google.colab import drive
drive.mount('/content/drive')



"""# Propriedades da imagem"""

img_PID_2024

"""Observe acima que a imagem carregada nada mais é do que um array bidimensional. Cada pixel é caracterizado por uma coordenada (x,y) e um valor de intensidade. O tamanho dessa matriz/imagem é determinada pelo número de colunas/largura (m) e linhas/altura (n) da matriz (m x n)."""

img_PID_2024.shape

img_PID_2024.max()

img_PID_2024.min()

"""Descubra o valor médio da intensidade dos pixels da imagem."""

intensity_mean = np.mean(img_PID_2024)
intensity_mean

"""# Visualizando uma imagem

Para visualizar a representação da imagem de fato, e não a matriz, precisamos utilizar a função ***plt.imshow()***.

\
Passamos como argumentos a imagem carregada, o mapa de cores utilizado e os valores mínimos e máximos que os pixels podem assumir.
"""

plt.imshow(img_PID_2024r, cmap='gray', vmin=0, vmax=250)

plt.imshow(cv2.cvtColor(img_PID_2024r, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.show()

"""# Printando shape e size"""

print(img_PID_2024r.shape)

print(img_PID_2024r.size)

"""# Imagem Redimensionada"""

image = Image.open("/content/968d4064-1c6a-40dd-a825-0d93debe5ad9.jpg")
new_image = image.resize((750, 200))
plt.imshow(new_image)

"""# Imagem Rotacionada"""

Original_Image = Image.open("/content/968d4064-1c6a-40dd-a825-0d93debe5ad9.jpg")
rotated_image = Original_Image.rotate(39)

plt.imshow(rotated_image)

"""Vale ressaltar que importamos a função Image da Biblioteca Pil do python para executar essa atividade"""